---
kind: pipeline
type: docker
name: test

steps:
  - name: lint
    image: golang:1.13
    commands:
      - go vet ./...

  - name: unit-test
    image: golang:1.13
    commands:
      - go test -coverprofile=coverage.out ./...

trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: release

steps:
  - name: download
    image: golang:1.13
    commands:
      - go mod download

  - name: build-darwin
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: darwin
      GOARCH: amd64
    commands:
      - mkdir darwin_amd64 && cp LICENSE README.md darwin_amd64
      - >
        go build 
        -o darwin_amd64/argocui
        -ldflags "-s -w -X github.com/hanjunlee/argocui/cmd.version=${DRONE_TAG} -X github.com/hanjunlee/argocui/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/argocui/cmd.build=${DRONE_BUILD_NUMBER}" 
        ./cmd/argocui/main.go
      - cd darwin_amd64 && tar -czf argocui_darwin_amd64.tar.gz argocui LICENSE README.md  
    depends_on:
      - download

  - name: build-linux
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - mkdir linux_amd64 && cp LICENSE README.md linux_amd64
      - >
        go build 
        -o linux_amd64/argocui
        -ldflags "-s -w -X github.com/hanjunlee/argocui/cmd.version=${DRONE_TAG} -X github.com/hanjunlee/argocui/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/argocui/cmd.build=${DRONE_BUILD_NUMBER}" 
        ./cmd/argocui/main.go
      - cd linux_amd64 && tar -czf argocui_linux_amd64.tar.gz argocui LICENSE README.md  
    depends_on:
      - download

  - name: build-windows
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: windows
      GOARCH: amd64
    commands:
      - mkdir windows_amd64 && cp LICENSE README.md windows_amd64
      - >
        go build 
        -o windows_amd64/argocui.exe 
        -ldflags "-s -w -X github.com/hanjunlee/argocui/cmd.version=${DRONE_TAG} -X github.com/hanjunlee/argocui/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/argocui/cmd.build=${DRONE_BUILD_NUMBER}" 
        ./cmd/argocui/main.go
      - cd windows_amd64 && tar -czf argocui_windows_amd64.tar.gz argocui.exe LICENSE README.md  
    depends_on:
      - download

  - name: aggregater
    image: golang:1.13
    commands:
      - mkdir dist
      - cp darwin_amd64/argocui_darwin_amd64.tar.gz linux_amd64/argocui_linux_amd64.tar.gz windows_amd64/argocui_windows_amd64.tar.gz dist/
      - ls dist/
    depends_on:
      - build-darwin
      - build-linux
      - build-windows

  - name: release
    image: plugins/github-release
    settings:
      title: ${DRONE_TAG}
      api_key: 
        from_secret: github_token
      files: dist/*
      checksum:
        - sha256
      draft: true
    depends_on:
      - aggregater
  
  # TODO: homebrew

trigger:
  ref:
    - refs/tags/v*.*.*
