---
kind: pipeline
type: docker
name: test

steps:
  - name: lint
    image: golang:1.13
    commands:
      - go vet ./...

  - name: unit-test
    image: golang:1.13
    commands:
      - go test -coverprofile=coverage.out ./...

trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: release

steps:
  - name: download
    image: golang:1.13
    commands:
      - go mod download

  - name: build-darwin
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: darwin
      GOARCH: amd64
    commands:
      - >
        go build \
        -o dist/acui_darwin_amd64 \
        -ldflags "-s -w -X github.com/hanjunlee/argocui/cmd.version=${DRONE_TAG} -X github.com/hanjunlee/argocui/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/argocui/cmd.build=${DRONE_BUILD_NUMBER}" \
        ./cmd
    depends_on:
      - download

  - name: build-linux
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - >
        go build \
        -o dist/acui_linux_amd64 \
        -ldflags "-s -w -X github.com/hanjunlee/argocui/cmd.version=${DRONE_TAG} -X github.com/hanjunlee/argocui/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/argocui/cmd.build=${DRONE_BUILD_NUMBER}" \
        ./cmd
    depends_on:
      - download

  - name: build-windows
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: windows
      GOARCH: amd64
    commands:
      - >
        go build \
        -o dist/acui_windows_amd64.exe \
        -ldflags "-s -w -X github.com/hanjunlee/argocui/cmd.version=${DRONE_TAG} -X github.com/hanjunlee/argocui/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/argocui/cmd.build=${DRONE_BUILD_NUMBER}" \
        ./cmd
    depends_on:
      - download
  
  
  - name: release
    image: plugins/github-release
    settings:
      title: ${DRONE_TAG}
      api_key: 
        from_secret: github_token
      files: dist/*
      checksum:
        - sha256
      draft: true
    depends_on:
      - build-darwin
      - build-linux
      - build-windows

  # TODO: upload to homebrew-argocui

trigger:
  ref:
    - refs/tags/*.*.*
